require "editor.options"
require "editor.keymaps"
require "editor.plugins"
require "editor.colorscheme"
require "editor.cmp"
require "editor.lsp"
require "editor.telescope"
require "editor.treesitter"
